test:
  adapter: postgresql
  host: localhost
  database: ruby_at_scale_test
  username: postgres
  password:

production:
  adapter: postgresql
  host: localhost
  database: ruby_at_scale_production
  username: postgres
  password:
